# Site settings
title: Fundacja Makerspace Lublin 
email: fundacja@makerspace-lbn.pl
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://makerspace-lbn.pl" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

collections:
  events:
    output: true
    permalink: /events/:path/
  workshops:
    output: true
    permalink: /workshops/:path/